[tool.poetry]
name = "chess-tuning-tools"
version = "0.4.0"
description = "A collection of tools for local and distributed tuning of chess engines."
authors = ["Karlson Pfannschmidt <kiudee@mail.upb.de>"]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English"
]
readme = "README.rst"
repository = "https://github.com/kiudee/chess-tuning-tools"
keywords = ["chess", "tuning", "optimization", "engine"]
documentation = "https://chess-tuning-tools.readthedocs.io"
packages = [
    {include = "tune"}
]

[tool.poetry.dependencies]
python = "^3.7"
bask = "^0.7.2"
Click = "^7.1.2"
numpy = "^1.19.1"
scipy = "^1.5.2"
scikit-optimize = "^0.7.4"
emcee = "^3.0.2"
joblib = {version = "^0.16.0", optional = true}
psycopg2 = {version = "^2.8.5", optional = true}
sqlalchemy = {version = "^1.3.18", optional = true}
pandas = {version = "^1.1.0", optional = true}
atomicwrites = "^1.4.0"

[tool.poetry.extras]
dist = ["joblib", "psycopg2", "sqlalchemy", "pandas"]

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
tune = "tune.cli:cli"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kiudee/chess-tuning-tools/issues"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
